/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
 *     it later on.
 *
 * OpenAPI spec version: v0.2.0-beta.13
 */
import { Checker, GetAppStateResponse, SaveAppStateResponse } from "./schemas";
import type { ErrorResponse, SaveAppStateRequest } from "./schemas";

export type getCheckerCheckerGetResponse200 = {
  data: Checker;
  status: 200;
};

export type getCheckerCheckerGetResponseSuccess =
  getCheckerCheckerGetResponse200 & {
    headers: Headers;
  };
export type getCheckerCheckerGetResponse = getCheckerCheckerGetResponseSuccess;

export const getGetCheckerCheckerGetUrl = () => {
  return `https://www.dev.sgdi.tech/api/wps/v1/state/checker`;
};

/**
 * Simple checker endpoint to be used by kubernetes probes
 * @summary Kubernetes Probe
 */
export const getCheckerCheckerGet = async (
  options?: RequestInit,
): Promise<getCheckerCheckerGetResponse> => {
  const res = await fetch(getGetCheckerCheckerGetUrl(), {
    ...options,
    method: "GET",
  });

  const contentType = (res.headers.get("content-type") ?? "").toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body
    ? contentType.includes("json")
      ? JSON.parse(body)
      : body
    : {};
  const data = contentType.includes("json")
    ? Checker.parse(parsedBody)
    : parsedBody;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getCheckerCheckerGetResponse;
};

export type postAppStatePostResponse200 = {
  data: SaveAppStateResponse;
  status: 200;
};

export type postAppStatePostResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type postAppStatePostResponseSuccess = postAppStatePostResponse200 & {
  headers: Headers;
};
export type postAppStatePostResponseError = postAppStatePostResponse400 & {
  headers: Headers;
};

export type postAppStatePostResponse =
  | postAppStatePostResponseSuccess
  | postAppStatePostResponseError;

export const getPostAppStatePostUrl = () => {
  return `https://www.dev.sgdi.tech/api/wps/v1/state/`;
};

/**
 * Save the given application state
 * @summary Save Application State
 */
export const postAppStatePost = async (
  saveAppStateRequest: SaveAppStateRequest,
  options?: RequestInit,
): Promise<postAppStatePostResponse> => {
  const res = await fetch(getPostAppStatePostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(saveAppStateRequest),
  });

  const contentType = (res.headers.get("content-type") ?? "").toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body
    ? contentType.includes("json")
      ? JSON.parse(body)
      : body
    : {};
  const data = contentType.includes("json")
    ? SaveAppStateResponse.parse(parsedBody)
    : parsedBody;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAppStatePostResponse;
};

export type getAppStateStateIdGetResponse200 = {
  data: GetAppStateResponse;
  status: 200;
};

export type getAppStateStateIdGetResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type getAppStateStateIdGetResponse404 = {
  data: ErrorResponse;
  status: 404;
};

export type getAppStateStateIdGetResponseSuccess =
  getAppStateStateIdGetResponse200 & {
    headers: Headers;
  };
export type getAppStateStateIdGetResponseError = (
  | getAppStateStateIdGetResponse400
  | getAppStateStateIdGetResponse404
) & {
  headers: Headers;
};

export type getAppStateStateIdGetResponse =
  | getAppStateStateIdGetResponseSuccess
  | getAppStateStateIdGetResponseError;

export const getGetAppStateStateIdGetUrl = (stateId: string) => {
  return `https://www.dev.sgdi.tech/api/wps/v1/state/${stateId}`;
};

/**
 * Retrieve an application state by ID
 * @summary Get Application State
 */
export const getAppStateStateIdGet = async (
  stateId: string,
  options?: RequestInit,
): Promise<getAppStateStateIdGetResponse> => {
  const res = await fetch(getGetAppStateStateIdGetUrl(stateId), {
    ...options,
    method: "GET",
  });

  const contentType = (res.headers.get("content-type") ?? "").toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const parsedBody = body
    ? contentType.includes("json")
      ? JSON.parse(body)
      : body
    : {};
  const data = contentType.includes("json")
    ? GetAppStateResponse.parse(parsedBody)
    : parsedBody;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAppStateStateIdGetResponse;
};
