// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  GetAppStateStateIdGetData,
  GetAppStateStateIdGetErrors,
  GetAppStateStateIdGetResponses,
  GetCheckerCheckerGetData,
  GetCheckerCheckerGetResponses,
  PostAppStatePostData,
  PostAppStatePostErrors,
  PostAppStatePostResponses,
} from "./types.gen";
import {
  zGetAppStateStateIdGetPath,
  zGetAppStateStateIdGetResponse,
  zGetCheckerCheckerGetResponse,
  zPostAppStatePostBody,
  zPostAppStatePostResponse,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Kubernetes Probe
 *
 * Simple checker endpoint to be used by kubernetes probes
 */
export const getCheckerCheckerGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCheckerCheckerGetData, ThrowOnError>,
): RequestResult<GetCheckerCheckerGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetCheckerCheckerGetResponses,
    unknown,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetCheckerCheckerGetResponse.parseAsync(data),
    url: "/checker",
    ...options,
  });

/**
 * Save Application State
 *
 * Save the given application state
 */
export const postAppStatePost = <ThrowOnError extends boolean = false>(
  options: Options<PostAppStatePostData, ThrowOnError>,
): RequestResult<
  PostAppStatePostResponses,
  PostAppStatePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostAppStatePostResponses,
    PostAppStatePostErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostAppStatePostBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zPostAppStatePostResponse.parseAsync(data),
    url: "/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Application State
 *
 * Retrieve an application state by ID
 */
export const getAppStateStateIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAppStateStateIdGetData, ThrowOnError>,
): RequestResult<
  GetAppStateStateIdGetResponses,
  GetAppStateStateIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAppStateStateIdGetResponses,
    GetAppStateStateIdGetErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetAppStateStateIdGetPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) =>
      await zGetAppStateStateIdGetResponse.parseAsync(data),
    url: "/{state_id}",
    ...options,
  });
