// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/wps/v1/state` | (string & {});
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  /**
   * Error
   *
   * Error text code
   */
  error: string;
  /**
   * Message
   *
   * Error message
   */
  message: string;
  /**
   * Detail
   *
   * Details on the error
   */
  detail?: unknown | null;
};

/**
 * GetAppStateResponse
 */
export type GetAppStateResponse = {
  state: StateV1Output;
  /**
   * Deprecated
   *
   * When true the application state version is deprecated
   */
  deprecated?: boolean;
  /**
   * Warning
   *
   * Warning message about deprecation flag
   */
  warning?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LayerDimensionsState
 */
export type LayerDimensionsState = {
  /**
   * Time dimension with current value
   */
  time?: TimeDimension;
};

/**
 * LayerState
 */
export type LayerStateInput = {
  /**
   * Layerurl
   *
   * URL of the layer to be displayed on the map
   */
  layerUrl: string;
  /**
   * Type of the layer (e.g. dataset, gpx, kml)
   */
  type: LayerTypeEnum;
  /**
   * Isvisible
   *
   * Whether the layer is visible on the map
   */
  isVisible?: boolean | null;
  /**
   * Opacity
   *
   * Opacity of the layer (between 0 and 1)
   */
  opacity?: number | null;
  /**
   * Dimensions of the layer (e.g. time dimension with current value)
   */
  dimensions?: LayerDimensionsState;
};

/**
 * LayerState
 */
export type LayerStateOutput = {
  /**
   * Layerurl
   *
   * URL of the layer to be displayed on the map
   */
  layerUrl: string;
  /**
   * Type of the layer (e.g. dataset, gpx, kml)
   */
  type: LayerTypeEnum;
  /**
   * Isvisible
   *
   * Whether the layer is visible on the map
   */
  isVisible?: boolean | null;
  /**
   * Opacity
   *
   * Opacity of the layer (between 0 and 1)
   */
  opacity?: number | null;
  /**
   * Dimensions of the layer (e.g. time dimension with current value)
   */
  dimensions?: LayerDimensionsState;
};

/**
 * LayerTypeEnum
 */
export type LayerTypeEnum = "dataset" | "gpx" | "kml";

/**
 * MapState
 */
export type MapState = {
  /**
   * Center
   *
   * Center of the map in [x, y] coordinates in lv95 / EPSG:2056
   */
  center?: [number, number] | null;
  /**
   * Zoom
   *
   * Zoom level of the map
   */
  zoom?: number | null;
  /**
   * Rotation
   *
   * Rotation of the map in radian
   */
  rotation?: number | null;
};

/**
 * SaveAppStateRequest
 */
export type SaveAppStateRequest = {
  /**
   * State of the application to save
   */
  state: StateV1Input;
};

/**
 * SaveAppStateResponse
 */
export type SaveAppStateResponse = {
  /**
   * Id
   *
   * ID of the saved state, to be used to retrieve the state later
   */
  id: string;
  /**
   * Deprecated
   *
   * When true the application state version provided is deprecated
   */
  deprecated?: boolean;
  /**
   * Warning
   *
   * Warning message about deprecation flag
   */
  warning?: string;
};

/**
 * StateV1
 *
 * State object of the application
 */
export type StateV1Input = {
  /**
   * State of the map
   */
  map?: MapState;
  /**
   * Layers
   *
   * List of layers to be displayed on the map
   */
  layers?: Array<LayerStateInput>;
};

/**
 * StateV1
 *
 * State object of the application
 */
export type StateV1Output = {
  /**
   * State of the map
   */
  map?: MapState;
  /**
   * Layers
   *
   * List of layers to be displayed on the map
   */
  layers?: Array<LayerStateOutput>;
};

/**
 * TimeDimension
 */
export type TimeDimension = {
  /**
   * Currentvalue
   *
   * Current selected time value
   */
  currentValue?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type PostAppStatePostData = {
  body: SaveAppStateRequest;
  path?: never;
  query?: never;
  url: "/";
};

export type PostAppStatePostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
};

export type PostAppStatePostError =
  PostAppStatePostErrors[keyof PostAppStatePostErrors];

export type PostAppStatePostResponses = {
  /**
   * Successful Response
   */
  200: SaveAppStateResponse;
};

export type PostAppStatePostResponse =
  PostAppStatePostResponses[keyof PostAppStatePostResponses];

export type GetAppStateStateIdGetData = {
  body?: never;
  path: {
    /**
     * State Id
     *
     * ID of the state
     */
    state_id: string;
  };
  query?: never;
  url: "/{state_id}";
};

export type GetAppStateStateIdGetErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
};

export type GetAppStateStateIdGetError =
  GetAppStateStateIdGetErrors[keyof GetAppStateStateIdGetErrors];

export type GetAppStateStateIdGetResponses = {
  /**
   * Successful Response
   */
  200: GetAppStateResponse;
};

export type GetAppStateStateIdGetResponse =
  GetAppStateStateIdGetResponses[keyof GetAppStateStateIdGetResponses];
