// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
  error: z.string(),
  message: z.string(),
  detail: z.unknown().nullish(),
});

/**
 * LayerTypeEnum
 */
export const zLayerTypeEnum = z.enum(["dataset", "gpx", "kml"]);

/**
 * MapState
 */
export const zMapState = z.object({
  center: z.tuple([z.number().gt(0), z.number().gt(0)]).nullish(),
  zoom: z.number().gte(1).lte(13).nullish(),
  rotation: z.number().gte(0).lte(6.283185307179586).nullish(),
});

/**
 * SaveAppStateResponse
 */
export const zSaveAppStateResponse = z.object({
  id: z.string().length(16),
  deprecated: z.boolean().optional().default(false),
  warning: z.string().optional().default(""),
});

/**
 * TimeDimension
 */
export const zTimeDimension = z.object({
  currentValue: z.string().max(50).nullish(),
});

/**
 * LayerDimensionsState
 */
export const zLayerDimensionsState = z.object({
  time: zTimeDimension.optional(),
});

/**
 * LayerState
 */
export const zLayerStateInput = z.object({
  layerUrl: z.url().min(1),
  type: zLayerTypeEnum,
  isVisible: z.boolean().nullish(),
  opacity: z.number().gte(0).lte(1).nullish(),
  dimensions: zLayerDimensionsState.optional(),
});

/**
 * LayerState
 */
export const zLayerStateOutput = z.object({
  layerUrl: z.url().min(1),
  type: zLayerTypeEnum,
  isVisible: z.boolean().nullish(),
  opacity: z.number().gte(0).lte(1).nullish(),
  dimensions: zLayerDimensionsState.optional(),
});

/**
 * StateV1
 *
 * State object of the application
 */
export const zStateV1Input = z.object({
  map: zMapState.optional(),
  layers: z.array(zLayerStateInput).optional(),
});

/**
 * SaveAppStateRequest
 */
export const zSaveAppStateRequest = z.object({
  state: zStateV1Input,
});

/**
 * StateV1
 *
 * State object of the application
 */
export const zStateV1Output = z.object({
  map: zMapState.optional(),
  layers: z.array(zLayerStateOutput).optional(),
});

/**
 * GetAppStateResponse
 */
export const zGetAppStateResponse = z.object({
  state: zStateV1Output,
  deprecated: z.boolean().optional().default(false),
  warning: z.string().optional().default(""),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zPostAppStatePostBody = zSaveAppStateRequest;

/**
 * Successful Response
 */
export const zPostAppStatePostResponse = zSaveAppStateResponse;

export const zGetAppStateStateIdGetPath = z.object({
  state_id: z.string().length(16),
});

/**
 * Successful Response
 */
export const zGetAppStateStateIdGetResponse = zGetAppStateResponse;
