/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ALL_YEARS_TIMESTAMP: typeof import('../src/utils/timeUtils').ALL_YEARS_TIMESTAMP
  const CURRENT_YEAR_TIMESTAMP: typeof import('../src/utils/timeUtils').CURRENT_YEAR_TIMESTAMP
  const CrossHairs: typeof import('../src/stores/position/types/crossHairs.enum').CrossHairs
  const DEFAULT_PROJECTION: typeof import('../src/stores/position/index').DEFAULT_PROJECTION
  const DrawingMode: typeof import('../src/stores/types').DrawingMode
  const EffectScope: typeof import('vue').EffectScope
  const LV03Format: typeof import('../src/utils/coordinates/coordinateFormat').LV03Format
  const LV95Format: typeof import('../src/utils/coordinates/coordinateFormat').LV95Format
  const MGRSFormat: typeof import('../src/utils/coordinates/coordinateFormat').MGRSFormat
  const MapModule: typeof import('../src/index').MapModule
  const MercatorFormat: typeof import('../src/utils/coordinates/coordinateFormat').MercatorFormat
  const PROJECTION_EPSG: typeof import('../src/index').PROJECTION_EPSG
  const SidebarType: typeof import('../src/stores/ui').SidebarType
  const TimeSlider: typeof import('../src/index').TimeSlider
  const UTMFormat: typeof import('../src/utils/coordinates/coordinateFormat').UTMFormat
  const VIEW_MIN_RESOLUTION: typeof import('../src/composables/useViewBasedOnProjection.composable').VIEW_MIN_RESOLUTION
  const WGS84Format: typeof import('../src/utils/coordinates/coordinateFormat').WGS84Format
  const WMS_TILE_SIZE: typeof import('../src/composables/olWMSLayer.composable').WMS_TILE_SIZE
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const allFormats: typeof import('../src/utils/coordinates/coordinateFormat').allFormats
  const centerEpsg4326: typeof import('../src/stores/position/getters/centerEpsg4326').default
  const computed: typeof import('vue').computed
  const convertYearToTimestamp: typeof import('../src/tools/timeslider/timeSliderUtils').convertYearToTimestamp
  const coordinateFormat: typeof import('../src/utils/coordinates/coordinateFormat').default
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const decreaseZoom: typeof import('../src/stores/position/actions/decreaseZoom').default
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const encodeUTM: typeof import('../src/utils/militaryGridProjection').encodeUTM
  const extent: typeof import('../src/stores/position/getters/extent').default
  const geoJsonStyleFromLiterals: typeof import('../src/utils/geoJsonStyleFromLiterals').default
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getDataServiceLinks: typeof import('../src/utils/recordUtils').getDataServiceLinks
  const getExtentOfGeometries: typeof import('../src/utils/geoJsonUtils').getExtentOfGeometries
  const getLetterDesignator: typeof import('../src/utils/militaryGridProjection').getLetterDesignator
  const getLinksByRel: typeof import('../src/utils/recordUtils').getLinksByRel
  const getOlImageStyleForShape: typeof import('../src/utils/geoJsonStyleFromLiterals').getOlImageStyleForShape
  const getTimeInfoFromWMSCapabilities: typeof import('../src/utils/timeUtils').getTimeInfoFromWMSCapabilities
  const getTimeInfoFromWMTSCapabilities: typeof import('../src/utils/timeUtils').getTimeInfoFromWMTSCapabilities
  const getYearFromGeoadminWMTSValue: typeof import('../src/tools/timeslider/timeSliderUtils').getYearFromGeoadminWMTSValue
  const getYearsWithData: typeof import('../src/tools/timeslider/timeSliderUtils').getYearsWithData
  const h: typeof import('vue').h
  const increaseZoom: typeof import('../src/stores/position/actions/increaseZoom').default
  const inject: typeof import('vue').inject
  const inverse: typeof import('../src/utils/militaryGridProjection').inverse
  const isExtentOnlyWithinLV95Bounds: typeof import('../src/stores/position/getters/isExtentOnlyWithinLV95Bounds').default
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const latLonToMGRS: typeof import('../src/utils/militaryGridProjection').latLonToMGRS
  const latLonToUTM: typeof import('../src/utils/militaryGridProjection').latLonToUTM
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const mouseTrackerUtils: typeof import('../src/utils/mouseTrackerUtils').default
  const nextTick: typeof import('vue').nextTick
  const normalizeAngle: typeof import('../src/stores/position/utils/normalizeAngle').normalizeAngle
  const olGPXLayerComposable: typeof import('../src/composables/olGPXLayer.composable').default
  const olGeoJSONLayerComposable: typeof import('../src/composables/olGeoJSONLayer.composable').default
  const olKMLLayerComposable: typeof import('../src/composables/olKMLLayer.composable').default
  const olKMZLayerComposable: typeof import('../src/composables/olKMZLayer.composable').default
  const olLocalGeoJSONLayerComposable: typeof import('../src/composables/olLocalGeoJSONLayer.composable').default
  const olVectorLayerComposable: typeof import('../src/composables/olVectorLayer.composable').default
  const olWMSLayerComposable: typeof import('../src/composables/olWMSLayer.composable').default
  const olWMTSLayerComposable: typeof import('../src/composables/olWMTSLayer.composable').default
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const position: typeof import('../src/stores/position/index').default
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const reprojectGeoJsonData: typeof import('../src/utils/geoJsonUtils').reprojectGeoJsonData
  const reprojectGeoJsonGeometry: typeof import('../src/utils/geoJsonUtils').reprojectGeoJsonGeometry
  const resolution: typeof import('../src/stores/position/getters/resolution').default
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setAutoRotation: typeof import('../src/stores/position/actions/setAutoRotation').default
  const setCameraPosition: typeof import('../src/stores/position/actions/setCameraPosition').default
  const setCenter: typeof import('../src/stores/position/actions/setCenter').default
  const setCrossHair: typeof import('../src/stores/position/actions/setCrossHair').default
  const setDisplayedFormat: typeof import('../src/stores/position/actions/setDisplayedFormat').default
  const setHasOrientation: typeof import('../src/stores/position/actions/setHasOrientation').default
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setProjection: typeof import('../src/stores/position/actions/setProjection').default
  const setRotation: typeof import('../src/stores/position/actions/setRotation').default
  const setZoom: typeof import('../src/stores/position/actions/setZoom').default
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const timeslider: typeof import('../src/tools/timeslider/index').default
  const toPoint: typeof import('../src/utils/militaryGridProjection').toPoint
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const transformIntoTurfEquivalent: typeof import('../src/utils/geoJsonUtils').transformIntoTurfEquivalent
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAddLayerToMapComposable: typeof import('../src/composables/useAddLayerToMap.composable').default
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDrawingStore: typeof import('../src/stores/types').useDrawingStore
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useMapStore: typeof import('../src/stores/map.store').useMapStore
  const useModel: typeof import('vue').useModel
  const usePositionStore: typeof import('../src/stores/position/position').usePositionStore
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUiStore: typeof import('../src/stores/ui').useUiStore
  const useViewBasedOnProjectionComposable: typeof import('../src/composables/useViewBasedOnProjection.composable').default
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const zoomToExtent: typeof import('../src/stores/position/actions/zoomToExtent').default
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { EPSG_4326_WGS84, EPSG_2056_CH1903 } from '../src/composables/types.d'
  import('../src/composables/types.d')
  // @ts-ignore
  export type { CrossHairs } from '../src/stores/position/types/crossHairs.enum'
  import('../src/stores/position/types/crossHairs.enum')
  // @ts-ignore
  export type { CameraPosition, PositionStoreState, PositionStoreGetters, PositionStore } from '../src/stores/position/types/position'
  import('../src/stores/position/types/position')
  // @ts-ignore
  export type { ActionDispatcher } from '../src/stores/types'
  import('../src/stores/types')
  // @ts-ignore
  export type { SidebarType } from '../src/stores/ui'
  import('../src/stores/ui')
  // @ts-ignore
  export type { LayerWithTime } from '../src/tools/timeslider/timeSliderUtils'
  import('../src/tools/timeslider/timeSliderUtils')
  // @ts-ignore
  export type { CoordinateFormat } from '../src/utils/coordinates/coordinateFormat'
  import('../src/utils/coordinates/coordinateFormat')
  // @ts-ignore
  export type { FeatureCollectionWithCRS } from '../src/utils/geoJsonUtils'
  import('../src/utils/geoJsonUtils')
  // @ts-ignore
  export type { UTM } from '../src/utils/militaryGridProjection'
  import('../src/utils/militaryGridProjection')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ALL_YEARS_TIMESTAMP: UnwrapRef<typeof import('../src/utils/timeUtils')['ALL_YEARS_TIMESTAMP']>
    readonly CURRENT_YEAR_TIMESTAMP: UnwrapRef<typeof import('../src/utils/timeUtils')['CURRENT_YEAR_TIMESTAMP']>
    readonly CrossHairs: UnwrapRef<typeof import('../src/stores/position/types/crossHairs.enum')['CrossHairs']>
    readonly DEFAULT_PROJECTION: UnwrapRef<typeof import('../src/stores/position/index')['DEFAULT_PROJECTION']>
    readonly DrawingMode: UnwrapRef<typeof import('../src/stores/types')['DrawingMode']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly LV03Format: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['LV03Format']>
    readonly LV95Format: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['LV95Format']>
    readonly MGRSFormat: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['MGRSFormat']>
    readonly MapModule: UnwrapRef<typeof import('../src/index')['MapModule']>
    readonly MercatorFormat: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['MercatorFormat']>
    readonly PROJECTION_EPSG: UnwrapRef<typeof import('../src/index')['PROJECTION_EPSG']>
    readonly SidebarType: UnwrapRef<typeof import('../src/stores/ui')['SidebarType']>
    readonly TimeSlider: UnwrapRef<typeof import('../src/index')['TimeSlider']>
    readonly UTMFormat: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['UTMFormat']>
    readonly VIEW_MIN_RESOLUTION: UnwrapRef<typeof import('../src/composables/useViewBasedOnProjection.composable')['VIEW_MIN_RESOLUTION']>
    readonly WGS84Format: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['WGS84Format']>
    readonly WMS_TILE_SIZE: UnwrapRef<typeof import('../src/composables/olWMSLayer.composable')['WMS_TILE_SIZE']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly allFormats: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['allFormats']>
    readonly centerEpsg4326: UnwrapRef<typeof import('../src/stores/position/getters/centerEpsg4326')['default']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly convertYearToTimestamp: UnwrapRef<typeof import('../src/tools/timeslider/timeSliderUtils')['convertYearToTimestamp']>
    readonly coordinateFormat: UnwrapRef<typeof import('../src/utils/coordinates/coordinateFormat')['default']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly decreaseZoom: UnwrapRef<typeof import('../src/stores/position/actions/decreaseZoom')['default']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly encodeUTM: UnwrapRef<typeof import('../src/utils/militaryGridProjection')['encodeUTM']>
    readonly extent: UnwrapRef<typeof import('../src/stores/position/getters/extent')['default']>
    readonly geoJsonStyleFromLiterals: UnwrapRef<typeof import('../src/utils/geoJsonStyleFromLiterals')['default']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getDataServiceLinks: UnwrapRef<typeof import('../src/utils/recordUtils')['getDataServiceLinks']>
    readonly getExtentOfGeometries: UnwrapRef<typeof import('../src/utils/geoJsonUtils')['getExtentOfGeometries']>
    readonly getLetterDesignator: UnwrapRef<typeof import('../src/utils/militaryGridProjection')['getLetterDesignator']>
    readonly getLinksByRel: UnwrapRef<typeof import('../src/utils/recordUtils')['getLinksByRel']>
    readonly getOlImageStyleForShape: UnwrapRef<typeof import('../src/utils/geoJsonStyleFromLiterals')['getOlImageStyleForShape']>
    readonly getTimeInfoFromWMSCapabilities: UnwrapRef<typeof import('../src/utils/timeUtils')['getTimeInfoFromWMSCapabilities']>
    readonly getTimeInfoFromWMTSCapabilities: UnwrapRef<typeof import('../src/utils/timeUtils')['getTimeInfoFromWMTSCapabilities']>
    readonly getYearFromGeoadminWMTSValue: UnwrapRef<typeof import('../src/tools/timeslider/timeSliderUtils')['getYearFromGeoadminWMTSValue']>
    readonly getYearsWithData: UnwrapRef<typeof import('../src/tools/timeslider/timeSliderUtils')['getYearsWithData']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly increaseZoom: UnwrapRef<typeof import('../src/stores/position/actions/increaseZoom')['default']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly inverse: UnwrapRef<typeof import('../src/utils/militaryGridProjection')['inverse']>
    readonly isExtentOnlyWithinLV95Bounds: UnwrapRef<typeof import('../src/stores/position/getters/isExtentOnlyWithinLV95Bounds')['default']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly latLonToMGRS: UnwrapRef<typeof import('../src/utils/militaryGridProjection')['latLonToMGRS']>
    readonly latLonToUTM: UnwrapRef<typeof import('../src/utils/militaryGridProjection')['latLonToUTM']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly mouseTrackerUtils: UnwrapRef<typeof import('../src/utils/mouseTrackerUtils')['default']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizeAngle: UnwrapRef<typeof import('../src/stores/position/utils/normalizeAngle')['normalizeAngle']>
    readonly olGPXLayerComposable: UnwrapRef<typeof import('../src/composables/olGPXLayer.composable')['default']>
    readonly olGeoJSONLayerComposable: UnwrapRef<typeof import('../src/composables/olGeoJSONLayer.composable')['default']>
    readonly olKMLLayerComposable: UnwrapRef<typeof import('../src/composables/olKMLLayer.composable')['default']>
    readonly olKMZLayerComposable: UnwrapRef<typeof import('../src/composables/olKMZLayer.composable')['default']>
    readonly olLocalGeoJSONLayerComposable: UnwrapRef<typeof import('../src/composables/olLocalGeoJSONLayer.composable')['default']>
    readonly olVectorLayerComposable: UnwrapRef<typeof import('../src/composables/olVectorLayer.composable')['default']>
    readonly olWMSLayerComposable: UnwrapRef<typeof import('../src/composables/olWMSLayer.composable')['default']>
    readonly olWMTSLayerComposable: UnwrapRef<typeof import('../src/composables/olWMTSLayer.composable')['default']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly position: UnwrapRef<typeof import('../src/stores/position/index')['default']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly reprojectGeoJsonData: UnwrapRef<typeof import('../src/utils/geoJsonUtils')['reprojectGeoJsonData']>
    readonly reprojectGeoJsonGeometry: UnwrapRef<typeof import('../src/utils/geoJsonUtils')['reprojectGeoJsonGeometry']>
    readonly resolution: UnwrapRef<typeof import('../src/stores/position/getters/resolution')['default']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setAutoRotation: UnwrapRef<typeof import('../src/stores/position/actions/setAutoRotation')['default']>
    readonly setCameraPosition: UnwrapRef<typeof import('../src/stores/position/actions/setCameraPosition')['default']>
    readonly setCenter: UnwrapRef<typeof import('../src/stores/position/actions/setCenter')['default']>
    readonly setCrossHair: UnwrapRef<typeof import('../src/stores/position/actions/setCrossHair')['default']>
    readonly setDisplayedFormat: UnwrapRef<typeof import('../src/stores/position/actions/setDisplayedFormat')['default']>
    readonly setHasOrientation: UnwrapRef<typeof import('../src/stores/position/actions/setHasOrientation')['default']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly setProjection: UnwrapRef<typeof import('../src/stores/position/actions/setProjection')['default']>
    readonly setRotation: UnwrapRef<typeof import('../src/stores/position/actions/setRotation')['default']>
    readonly setZoom: UnwrapRef<typeof import('../src/stores/position/actions/setZoom')['default']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly timeslider: UnwrapRef<typeof import('../src/tools/timeslider/index')['default']>
    readonly toPoint: UnwrapRef<typeof import('../src/utils/militaryGridProjection')['toPoint']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly transformIntoTurfEquivalent: UnwrapRef<typeof import('../src/utils/geoJsonUtils')['transformIntoTurfEquivalent']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAddLayerToMapComposable: UnwrapRef<typeof import('../src/composables/useAddLayerToMap.composable')['default']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDrawingStore: UnwrapRef<typeof import('../src/stores/types')['useDrawingStore']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useMapStore: UnwrapRef<typeof import('../src/stores/map.store')['useMapStore']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly usePositionStore: UnwrapRef<typeof import('../src/stores/position/position')['usePositionStore']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useUiStore: UnwrapRef<typeof import('../src/stores/ui')['useUiStore']>
    readonly useViewBasedOnProjectionComposable: UnwrapRef<typeof import('../src/composables/useViewBasedOnProjection.composable')['default']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly zoomToExtent: UnwrapRef<typeof import('../src/stores/position/actions/zoomToExtent')['default']>
  }
}