/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
 *     it later on.
 *
 * OpenAPI spec version: v0.2.0-beta.13
 */
import { z as zod } from "zod";

export const ErrorResponse = zod.object({
  error: zod.string().describe("Error text code"),
  message: zod.string().describe("Error message"),
  detail: zod
    .union([zod.unknown(), zod.null()])
    .optional()
    .describe("Details on the error"),
});

export type ErrorResponse = zod.input<typeof ErrorResponse>;
export type ErrorResponseOutput = zod.output<typeof ErrorResponse>;
