/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
 *     it later on.
 *
 * OpenAPI spec version: v0.2.0-beta.13
 */
import { z as zod } from "zod";

export const LayerTypeEnum = zod.enum(["dataset", "gpx", "kml"]);

export type LayerTypeEnum = zod.input<typeof LayerTypeEnum>;
export type LayerTypeEnumOutput = zod.output<typeof LayerTypeEnum>;
