/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
 *     it later on.
 *
 * OpenAPI spec version: v0.2.0-beta.13
 */
import { z as zod } from "zod";

export const mapStateZoomOneMax = 13;

export const mapStateRotationOneMin = 0;
export const mapStateRotationOneMax = 6.283185307179586;

export const MapState = zod.object({
  center: zod
    .union([
      zod.tuple([
        zod.number().describe("Coordinate x in LV95 \/ EPSG:2056 (meters)"),
        zod.number().describe("Coordinate y in LV95 \/ EPSG:2056 (meters)"),
      ]),
      zod.null(),
    ])
    .optional()
    .describe("Center of the map in [x, y] coordinates in lv95 \/ EPSG:2056"),
  zoom: zod
    .union([zod.number().min(1).max(mapStateZoomOneMax), zod.null()])
    .optional()
    .describe("Zoom level of the map"),
  rotation: zod
    .union([
      zod.number().min(mapStateRotationOneMin).max(mapStateRotationOneMax),
      zod.null(),
    ])
    .optional()
    .describe("Rotation of the map in radian"),
});

export type MapState = zod.input<typeof MapState>;
export type MapStateOutput = zod.output<typeof MapState>;
