/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
 *     it later on.
 *
 * OpenAPI spec version: v0.2.0-beta.13
 */
import { z as zod } from "zod";

export const saveAppStateResponseIdMin = 16;
export const saveAppStateResponseIdMax = 16;

export const saveAppStateResponseDeprecatedDefault = false;
export const saveAppStateResponseWarningDefault = ``;
export const SaveAppStateResponse = zod.object({
  id: zod
    .string()
    .min(saveAppStateResponseIdMin)
    .max(saveAppStateResponseIdMax)
    .describe("ID of the saved state, to be used to retrieve the state later"),
  deprecated: zod
    .boolean()
    .default(saveAppStateResponseDeprecatedDefault)
    .describe("When true the application state version provided is deprecated"),
  warning: zod
    .string()
    .default(saveAppStateResponseWarningDefault)
    .describe("Warning message about deprecation flag"),
});

export type SaveAppStateResponse = zod.input<typeof SaveAppStateResponse>;
export type SaveAppStateResponseOutput = zod.output<
  typeof SaveAppStateResponse
>;
