/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
    it later on.
    
 * OpenAPI spec version: v0.2.0-beta.10
 */
import { z as zod } from 'zod'

export const Checker = zod.object({
    success: zod.boolean().describe('True when the probe is successful, false otherwise'),
    message: zod.string().describe('Failure explanation in case of failure, otherwise OK'),
    version: zod.string().describe('Version of the service'),
})

export type Checker = zod.input<typeof Checker>
export type CheckerOutput = zod.output<typeof Checker>
