/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const getAppStateResponseStateMapCenterDefault = [2660000, 1190000] as [number, number]
export const getAppStateResponseStateMapZoomDefault = 1
export const getAppStateResponseStateMapZoomMax = 13

export const getAppStateResponseStateMapRotationDefault = 0
export const getAppStateResponseStateMapRotationMin = 0
export const getAppStateResponseStateMapRotationMax = 6.283185307179586

export const getAppStateResponseStateLayersItemIsVisibleDefault = true
export const getAppStateResponseStateLayersItemOpacityDefault = 1
export const getAppStateResponseStateLayersItemOpacityMin = 0
export const getAppStateResponseStateLayersItemOpacityMax = 1

export const getAppStateResponseStateLayersItemDimensionsTimeCurrentValueDefault = `current`
export const getAppStateResponseDeprecatedDefault = false
export const getAppStateResponseWarningDefault = ``
export const GetAppStateResponse = zod.object({
    version: zod.string().describe('Version of the state object: `major.minor`'),
    state: zod
        .object({
            map: zod
                .object({
                    center: zod
                        .tuple([
                            zod
                                .number()
                                // .gt(getAppStateResponseStateMapCenter0ItemExclusiveMin)
                                .describe('Coordinate x in LV95 \/ EPSG:2056 (meters)'),
                            zod
                                .number()
                                // .gt(getAppStateResponseStateMapCenter1ItemExclusiveMin)
                                .describe('Coordinate y in LV95 \/ EPSG:2056 (meters)'),
                        ])
                        .default(getAppStateResponseStateMapCenterDefault)
                        .describe('Center of the map in [x, y] coordinates in lv95 \/ EPSG:2056'),
                    zoom: zod
                        .number()
                        .min(1)
                        .max(getAppStateResponseStateMapZoomMax)
                        .default(getAppStateResponseStateMapZoomDefault)
                        .describe('Zoom level of the map'),
                    rotation: zod
                        .number()
                        .min(getAppStateResponseStateMapRotationMin)
                        .max(getAppStateResponseStateMapRotationMax)
                        .default(getAppStateResponseStateMapRotationDefault)
                        .describe('Rotation of the map in radian'),
                })
                .optional()
                .describe('State of the map'),
            layers: zod
                .array(
                    zod.object({
                        layerUrl: zod
                            .url()
                            .min(1)
                            .describe('URL of the layer to be displayed on the map'),
                        type: zod
                            .enum(['dataset', 'gpx', 'kml'])
                            .describe('Type of the layer (e.g. dataset, gpx, kml)'),
                        isVisible: zod
                            .boolean()
                            .default(getAppStateResponseStateLayersItemIsVisibleDefault)
                            .describe('Whether the layer is visible on the map'),
                        opacity: zod
                            .number()
                            .min(getAppStateResponseStateLayersItemOpacityMin)
                            .max(getAppStateResponseStateLayersItemOpacityMax)
                            .default(getAppStateResponseStateLayersItemOpacityDefault)
                            .describe('Opacity of the layer (between 0 and 1)'),
                        dimensions: zod
                            .object({
                                time: zod
                                    .object({
                                        currentValue: zod
                                            .union([zod.iso.datetime({}), zod.literal('current')])
                                            .default(
                                                getAppStateResponseStateLayersItemDimensionsTimeCurrentValueDefault
                                            )
                                            .describe('Current selected time value'),
                                    })
                                    .optional()
                                    .describe('Time dimension with current value'),
                            })
                            .optional()
                            .describe(
                                'Dimensions of the layer (e.g. time dimension with current value)'
                            ),
                    })
                )
                .optional()
                .describe('List of layers to be displayed on the map'),
        })
        .describe('State object of the application'),
    deprecated: zod
        .boolean()
        .default(getAppStateResponseDeprecatedDefault)
        .describe('When true the application state version is deprecated'),
    warning: zod
        .string()
        .default(getAppStateResponseWarningDefault)
        .describe('Warning message about deprecation flag'),
})

export type GetAppStateResponse = zod.input<typeof GetAppStateResponse>
export type GetAppStateResponseOutput = zod.output<typeof GetAppStateResponse>
