/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
    it later on.
    
 * OpenAPI spec version: v0.2.0-beta.10
 */
import { z as zod } from 'zod'

export const layerStateInputOpacityOneMin = 0
export const layerStateInputOpacityOneMax = 1

export const LayerStateInput = zod.object({
    layerUrl: zod.url().min(1).describe('URL of the layer to be displayed on the map'),
    type: zod
        .enum(['dataset', 'gpx', 'kml'])
        .describe('Type of the layer (e.g. dataset, gpx, kml)'),
    isVisible: zod
        .union([zod.boolean(), zod.null()])
        .optional()
        .describe('Whether the layer is visible on the map'),
    opacity: zod
        .union([
            zod.number().min(layerStateInputOpacityOneMin).max(layerStateInputOpacityOneMax),
            zod.null(),
        ])
        .optional()
        .describe('Opacity of the layer (between 0 and 1)'),
    dimensions: zod
        .object({
            time: zod
                .object({
                    currentValue: zod
                        .union([
                            zod.iso.datetime({ offset: true }),
                            zod.literal('current'),
                            zod.null(),
                        ])
                        .optional()
                        .describe('Current selected time value'),
                })
                .optional()
                .describe('Time dimension with current value'),
        })
        .optional()
        .describe('Dimensions of the layer (e.g. time dimension with current value)'),
})

export type LayerStateInput = zod.input<typeof LayerStateInput>
export type LayerStateInputOutput = zod.output<typeof LayerStateInput>
