/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.
        
 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const layerStateIsVisibleDefault = true
export const layerStateOpacityDefault = 1
export const layerStateOpacityMin = 0
export const layerStateOpacityMax = 1

export const layerStateDimensionsTimeCurrentValueDefault = `current`
export const LayerState = zod.object({
    layerUrl: zod.url().min(1).describe('URL of the layer to be displayed on the map'),
    type: zod
        .enum(['dataset', 'gpx', 'kml'])
        .describe('Type of the layer (e.g. dataset, gpx, kml)'),
    isVisible: zod
        .boolean()
        .default(layerStateIsVisibleDefault)
        .describe('Whether the layer is visible on the map'),
    opacity: zod
        .number()
        .min(layerStateOpacityMin)
        .max(layerStateOpacityMax)
        .default(layerStateOpacityDefault)
        .describe('Opacity of the layer (between 0 and 1)'),
    dimensions: zod
        .object({
            time: zod
                .object({
                    currentValue: zod
                        .union([zod.iso.datetime({}), zod.literal('current')])
                        .default(layerStateDimensionsTimeCurrentValueDefault)
                        .describe('Current selected time value'),
                })
                .optional()
                .describe('Time dimension with current value'),
        })
        .optional()
        .describe('Dimensions of the layer (e.g. time dimension with current value)'),
})

export type LayerState = zod.input<typeof LayerState>
export type LayerStateOutput = zod.output<typeof LayerState>
