/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.
        
 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const layerDimensionsStateTimeCurrentValueDefault = `current`
export const LayerDimensionsState = zod.object({
    time: zod
        .object({
            currentValue: zod
                .union([zod.iso.datetime({}), zod.literal('current')])
                .default(layerDimensionsStateTimeCurrentValueDefault)
                .describe('Current selected time value'),
        })
        .optional()
        .describe('Time dimension with current value'),
})

export type LayerDimensionsState = zod.input<typeof LayerDimensionsState>
export type LayerDimensionsStateOutput = zod.output<typeof LayerDimensionsState>
