/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const mapStateCenterDefault = [2660000, 1190000] as [number, number]
export const mapStateZoomDefault = 1
export const mapStateZoomMax = 13

export const mapStateRotationDefault = 0
export const mapStateRotationMin = 0
export const mapStateRotationMax = 6.283185307179586

export const MapState = zod.object({
    center: zod
        .tuple([
            zod
                .number()
                // .gt(mapStateCenter0ItemExclusiveMin)
                .describe('Coordinate x in LV95 \/ EPSG:2056 (meters)'),
            zod
                .number()
                // .gt(mapStateCenter1ItemExclusiveMin)
                .describe('Coordinate y in LV95 \/ EPSG:2056 (meters)'),
        ])
        .default(mapStateCenterDefault)
        .describe('Center of the map in [x, y] coordinates in lv95 \/ EPSG:2056'),
    zoom: zod
        .number()
        .min(1)
        .max(mapStateZoomMax)
        .default(mapStateZoomDefault)
        .describe('Zoom level of the map'),
    rotation: zod
        .number()
        .min(mapStateRotationMin)
        .max(mapStateRotationMax)
        .default(mapStateRotationDefault)
        .describe('Rotation of the map in radian'),
})

export type MapState = zod.input<typeof MapState>
export type MapStateOutput = zod.output<typeof MapState>
