/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const postAppStateApiStatePostBodyStateMapCenterDefault = [2660000, 1190000] as [
    number,
    number,
]
export const postAppStateApiStatePostBodyStateMapZoomDefault = 1
export const postAppStateApiStatePostBodyStateMapZoomMax = 13

export const postAppStateApiStatePostBodyStateMapRotationDefault = 0
export const postAppStateApiStatePostBodyStateMapRotationMin = 0
export const postAppStateApiStatePostBodyStateMapRotationMax = 6.283185307179586

export const postAppStateApiStatePostBodyStateLayersItemIsVisibleDefault = true
export const postAppStateApiStatePostBodyStateLayersItemOpacityDefault = 1
export const postAppStateApiStatePostBodyStateLayersItemOpacityMin = 0
export const postAppStateApiStatePostBodyStateLayersItemOpacityMax = 1

export const postAppStateApiStatePostBodyStateLayersItemDimensionsTimeCurrentValueDefault = `current`
export const PostAppStateApiStatePostBody = zod.object({
    version: zod.string().describe('Version of the state object: `major.minor`'),
    state: zod
        .object({
            map: zod
                .object({
                    center: zod
                        .tuple([
                            zod
                                .number()
                                // .gt(postAppStateApiStatePostBodyStateMapCenter0ItemExclusiveMin)
                                .describe('Coordinate x in LV95 \/ EPSG:2056 (meters)'),
                            zod
                                .number()
                                // .gt(postAppStateApiStatePostBodyStateMapCenter1ItemExclusiveMin)
                                .describe('Coordinate y in LV95 \/ EPSG:2056 (meters)'),
                        ])
                        .default(postAppStateApiStatePostBodyStateMapCenterDefault)
                        .describe('Center of the map in [x, y] coordinates in lv95 \/ EPSG:2056'),
                    zoom: zod
                        .number()
                        .min(1)
                        .max(postAppStateApiStatePostBodyStateMapZoomMax)
                        .default(postAppStateApiStatePostBodyStateMapZoomDefault)
                        .describe('Zoom level of the map'),
                    rotation: zod
                        .number()
                        .min(postAppStateApiStatePostBodyStateMapRotationMin)
                        .max(postAppStateApiStatePostBodyStateMapRotationMax)
                        .default(postAppStateApiStatePostBodyStateMapRotationDefault)
                        .describe('Rotation of the map in radian'),
                })
                .optional()
                .describe('State of the map'),
            layers: zod
                .array(
                    zod.object({
                        layerUrl: zod
                            .url()
                            .min(1)
                            .describe('URL of the layer to be displayed on the map'),
                        type: zod
                            .enum(['dataset', 'gpx', 'kml'])
                            .describe('Type of the layer (e.g. dataset, gpx, kml)'),
                        isVisible: zod
                            .boolean()
                            .default(postAppStateApiStatePostBodyStateLayersItemIsVisibleDefault)
                            .describe('Whether the layer is visible on the map'),
                        opacity: zod
                            .number()
                            .min(postAppStateApiStatePostBodyStateLayersItemOpacityMin)
                            .max(postAppStateApiStatePostBodyStateLayersItemOpacityMax)
                            .default(postAppStateApiStatePostBodyStateLayersItemOpacityDefault)
                            .describe('Opacity of the layer (between 0 and 1)'),
                        dimensions: zod
                            .object({
                                time: zod
                                    .object({
                                        currentValue: zod
                                            .union([zod.iso.datetime({}), zod.literal('current')])
                                            .default(
                                                postAppStateApiStatePostBodyStateLayersItemDimensionsTimeCurrentValueDefault
                                            )
                                            .describe('Current selected time value'),
                                    })
                                    .optional()
                                    .describe('Time dimension with current value'),
                            })
                            .optional()
                            .describe(
                                'Dimensions of the layer (e.g. time dimension with current value)'
                            ),
                    })
                )
                .optional()
                .describe('List of layers to be displayed on the map'),
        })
        .describe('State of the application to save'),
})

export type PostAppStateApiStatePostBody = zod.input<typeof PostAppStateApiStatePostBody>
export type PostAppStateApiStatePostBodyOutput = zod.output<typeof PostAppStateApiStatePostBody>
