/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
    it later on.

 * OpenAPI spec version: v0.2.0-beta.10
 */
import { z as zod } from 'zod'

export const postAppStatePostBodyStateMapZoomOneMax = 13

export const postAppStatePostBodyStateMapRotationOneMin = 0
export const postAppStatePostBodyStateMapRotationOneMax = 6.283185307179586

export const postAppStatePostBodyStateLayersItemOpacityOneMin = 0
export const postAppStatePostBodyStateLayersItemOpacityOneMax = 1

export const PostAppStatePostBody = zod.object({
    state: zod
        .object({
            map: zod
                .object({
                    center: zod
                        .union([
                            zod.tuple([
                                zod
                                    .number()
                                    // .gt(postAppStatePostBodyStateMapCenterOne0ItemExclusiveMin)
                                    .describe('Coordinate x in LV95 \/ EPSG:2056 (meters)'),
                                zod
                                    .number()
                                    // .gt(postAppStatePostBodyStateMapCenterOne1ItemExclusiveMin)
                                    .describe('Coordinate y in LV95 \/ EPSG:2056 (meters)'),
                            ]),
                            zod.null(),
                        ])
                        .optional()
                        .describe('Center of the map in [x, y] coordinates in lv95 \/ EPSG:2056'),
                    zoom: zod
                        .union([
                            zod.number().min(1).max(postAppStatePostBodyStateMapZoomOneMax),
                            zod.null(),
                        ])
                        .optional()
                        .describe('Zoom level of the map'),
                    rotation: zod
                        .union([
                            zod
                                .number()
                                .min(postAppStatePostBodyStateMapRotationOneMin)
                                .max(postAppStatePostBodyStateMapRotationOneMax),
                            zod.null(),
                        ])
                        .optional()
                        .describe('Rotation of the map in radian'),
                })
                .optional()
                .describe('State of the map'),
            layers: zod
                .array(
                    zod.object({
                        layerUrl: zod
                            .url()
                            .min(1)
                            .describe('URL of the layer to be displayed on the map'),
                        type: zod
                            .enum(['dataset', 'gpx', 'kml'])
                            .describe('Type of the layer (e.g. dataset, gpx, kml)'),
                        isVisible: zod
                            .union([zod.boolean(), zod.null()])
                            .optional()
                            .describe('Whether the layer is visible on the map'),
                        opacity: zod
                            .union([
                                zod
                                    .number()
                                    .min(postAppStatePostBodyStateLayersItemOpacityOneMin)
                                    .max(postAppStatePostBodyStateLayersItemOpacityOneMax),
                                zod.null(),
                            ])
                            .optional()
                            .describe('Opacity of the layer (between 0 and 1)'),
                        dimensions: zod
                            .object({
                                time: zod
                                    .object({
                                        currentValue: zod
                                            .union([
                                                zod.iso.datetime({ offset: true }),
                                                zod.literal('current'),
                                                zod.null(),
                                            ])
                                            .optional()
                                            .describe('Current selected time value'),
                                    })
                                    .optional()
                                    .describe('Time dimension with current value'),
                            })
                            .optional()
                            .describe(
                                'Dimensions of the layer (e.g. time dimension with current value)'
                            ),
                    })
                )
                .optional()
                .describe('List of layers to be displayed on the map'),
        })
        .describe('State of the application to save'),
})

export type PostAppStatePostBody = zod.input<typeof PostAppStatePostBody>
export type PostAppStatePostBodyOutput = zod.output<typeof PostAppStatePostBody>
