/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const saveAppStateRequestStateMapCenterDefault = [2660000, 1190000] as [number, number]
export const saveAppStateRequestStateMapZoomDefault = 1
export const saveAppStateRequestStateMapZoomMax = 13

export const saveAppStateRequestStateMapRotationDefault = 0
export const saveAppStateRequestStateMapRotationMin = 0
export const saveAppStateRequestStateMapRotationMax = 6.283185307179586

export const saveAppStateRequestStateLayersItemIsVisibleDefault = true
export const saveAppStateRequestStateLayersItemOpacityDefault = 1
export const saveAppStateRequestStateLayersItemOpacityMin = 0
export const saveAppStateRequestStateLayersItemOpacityMax = 1

export const saveAppStateRequestStateLayersItemDimensionsTimeCurrentValueDefault = `current`
export const SaveAppStateRequest = zod.object({
    version: zod.string().describe('Version of the state object: `major.minor`'),
    state: zod
        .object({
            map: zod
                .object({
                    center: zod
                        .tuple([
                            zod
                                .number()
                                // .gt(saveAppStateRequestStateMapCenter0ItemExclusiveMin)
                                .describe('Coordinate x in LV95 / EPSG:2056 (meters)'),
                            zod
                                .number()
                                // .gt(saveAppStateRequestStateMapCenter1ItemExclusiveMin)
                                .describe('Coordinate y in LV95 / EPSG:2056 (meters)'),
                        ])
                        .default(saveAppStateRequestStateMapCenterDefault)
                        .describe('Center of the map in [x, y] coordinates in lv95 \/ EPSG:2056'),
                    zoom: zod
                        .number()
                        .min(1)
                        .max(saveAppStateRequestStateMapZoomMax)
                        .default(saveAppStateRequestStateMapZoomDefault)
                        .describe('Zoom level of the map'),
                    rotation: zod
                        .number()
                        .min(saveAppStateRequestStateMapRotationMin)
                        .max(saveAppStateRequestStateMapRotationMax)
                        .default(saveAppStateRequestStateMapRotationDefault)
                        .describe('Rotation of the map in radian'),
                })
                .optional()
                .describe('State of the map'),
            layers: zod
                .array(
                    zod.object({
                        layerUrl: zod
                            .url()
                            .min(1)
                            .describe('URL of the layer to be displayed on the map'),
                        type: zod
                            .enum(['dataset', 'gpx', 'kml'])
                            .describe('Type of the layer (e.g. dataset, gpx, kml)'),
                        isVisible: zod
                            .boolean()
                            .default(saveAppStateRequestStateLayersItemIsVisibleDefault)
                            .describe('Whether the layer is visible on the map'),
                        opacity: zod
                            .number()
                            .min(saveAppStateRequestStateLayersItemOpacityMin)
                            .max(saveAppStateRequestStateLayersItemOpacityMax)
                            .default(saveAppStateRequestStateLayersItemOpacityDefault)
                            .describe('Opacity of the layer (between 0 and 1)'),
                        dimensions: zod
                            .object({
                                time: zod
                                    .object({
                                        currentValue: zod
                                            .union([zod.iso.datetime({}), zod.literal('current')])
                                            .default(
                                                saveAppStateRequestStateLayersItemDimensionsTimeCurrentValueDefault
                                            )
                                            .describe('Current selected time value'),
                                    })
                                    .optional()
                                    .describe('Time dimension with current value'),
                            })
                            .optional()
                            .describe(
                                'Dimensions of the layer (e.g. time dimension with current value)'
                            ),
                    })
                )
                .optional()
                .describe('List of layers to be displayed on the map'),
        })
        .describe('State of the application to save'),
})

export type SaveAppStateRequest = zod.input<typeof SaveAppStateRequest>
export type SaveAppStateRequestOutput = zod.output<typeof SaveAppStateRequest>
