/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const stateV1MapCenterDefault = [2660000, 1190000] as [number, number]
export const stateV1MapZoomDefault = 1
export const stateV1MapZoomMax = 13

export const stateV1MapRotationDefault = 0
export const stateV1MapRotationMin = 0
export const stateV1MapRotationMax = 6.283185307179586

export const stateV1LayersItemIsVisibleDefault = true
export const stateV1LayersItemOpacityDefault = 1
export const stateV1LayersItemOpacityMin = 0
export const stateV1LayersItemOpacityMax = 1

export const stateV1LayersItemDimensionsTimeCurrentValueDefault = `current`
export const StateV1 = zod
    .object({
        map: zod
            .object({
                center: zod
                    .tuple([
                        zod
                            .number()
                            // .gt(stateV1MapCenter0ItemExclusiveMin)
                            .describe('Coordinate x in LV95 \/ EPSG:2056 (meters)'),
                        zod
                            .number()
                            // .gt(stateV1MapCenter1ItemExclusiveMin)
                            .describe('Coordinate y in LV95 \/ EPSG:2056 (meters)'),
                    ])
                    .default(stateV1MapCenterDefault)
                    .describe('Center of the map in [x, y] coordinates in lv95 \/ EPSG:2056'),
                zoom: zod
                    .number()
                    .min(1)
                    .max(stateV1MapZoomMax)
                    .default(stateV1MapZoomDefault)
                    .describe('Zoom level of the map'),
                rotation: zod
                    .number()
                    .min(stateV1MapRotationMin)
                    .max(stateV1MapRotationMax)
                    .default(stateV1MapRotationDefault)
                    .describe('Rotation of the map in radian'),
            })
            .optional()
            .describe('State of the map'),
        layers: zod
            .array(
                zod.object({
                    layerUrl: zod
                        .url()
                        .min(1)
                        .describe('URL of the layer to be displayed on the map'),
                    type: zod
                        .enum(['dataset', 'gpx', 'kml'])
                        .describe('Type of the layer (e.g. dataset, gpx, kml)'),
                    isVisible: zod
                        .boolean()
                        .default(stateV1LayersItemIsVisibleDefault)
                        .describe('Whether the layer is visible on the map'),
                    opacity: zod
                        .number()
                        .min(stateV1LayersItemOpacityMin)
                        .max(stateV1LayersItemOpacityMax)
                        .default(stateV1LayersItemOpacityDefault)
                        .describe('Opacity of the layer (between 0 and 1)'),
                    dimensions: zod
                        .object({
                            time: zod
                                .object({
                                    currentValue: zod
                                        .union([zod.iso.datetime({}), zod.literal('current')])
                                        .default(stateV1LayersItemDimensionsTimeCurrentValueDefault)
                                        .describe('Current selected time value'),
                                })
                                .optional()
                                .describe('Time dimension with current value'),
                        })
                        .optional()
                        .describe(
                            'Dimensions of the layer (e.g. time dimension with current value)'
                        ),
                })
            )
            .optional()
            .describe('List of layers to be displayed on the map'),
    })
    .describe('State object of the application')

export type StateV1 = zod.input<typeof StateV1>
export type StateV1Output = zod.output<typeof StateV1>
