/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.
        
 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const timeDimensionCurrentValueDefault = `current`
export const TimeDimension = zod.object({
    currentValue: zod
        .union([zod.iso.datetime({}), zod.literal('current')])
        .default(timeDimensionCurrentValueDefault)
        .describe('Current selected time value'),
})

export type TimeDimension = zod.input<typeof TimeDimension>
export type TimeDimensionOutput = zod.output<typeof TimeDimension>
