/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.
        
 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { z as zod } from 'zod'

export const ValidationError = zod.object({
    loc: zod.array(zod.union([zod.string(), zod.number()])),
    msg: zod.string(),
    type: zod.string(),
    input: zod.unknown().optional(),
    ctx: zod.looseObject({}).optional(),
})

export type ValidationError = zod.input<typeof ValidationError>
export type ValidationErrorOutput = zod.output<typeof ValidationError>
