/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    LucideIcon: typeof import('./src/components/LucideIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanelButton: typeof import('./src/components/SearchPanelButton.vue')['default']
    SidebarButton: typeof import('./src/components/SidebarButton.vue')['default']
  }
}
