/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
export interface Checker {
    /** True when the probe is successful, false otherwise */
    success: boolean
    /** Failure explanation in case of failure, otherwise OK */
    message: string
    /** Version of the service */
    version: string
}

export interface ErrorResponse {
    /** Error text code */
    error: string
    /** Error message */
    message: string
    /** Details on the error */
    detail?: unknown | null
}

export interface MapState {
    /**
     * Center of the map in [x, y] coordinates in lv95 / EPSG:2056
     * @minItems 2
     * @maxItems 2
     */
    center?: [number, number]
    /**
     * Zoom level of the map
     * @minimum 1
     * @maximum 13
     */
    zoom?: number
    /**
     * Rotation of the map in radian
     * @minimum 0
     * @maximum 6.283185307179586
     */
    rotation?: number
}

export type LayerTypeEnum = (typeof LayerTypeEnum)[keyof typeof LayerTypeEnum]

export const LayerTypeEnum = {
    dataset: 'dataset',
    gpx: 'gpx',
    kml: 'kml',
} as const

export interface TimeDimension {
    /** Current selected time value */
    currentValue?: string | 'current'
}

export interface LayerDimensionsState {
    /** Time dimension with current value */
    time?: TimeDimension
}

export interface LayerState {
    /**
     * URL of the layer to be displayed on the map
     * @minLength 1
     */
    layerUrl: string
    /** Type of the layer (e.g. dataset, gpx, kml) */
    type: LayerTypeEnum
    /** Whether the layer is visible on the map */
    isVisible?: boolean
    /**
     * Opacity of the layer (between 0 and 1)
     * @minimum 0
     * @maximum 1
     */
    opacity?: number
    /** Dimensions of the layer (e.g. time dimension with current value) */
    dimensions?: LayerDimensionsState
}

/**
 * State object of the application
 */
export interface StateV1 {
    /** State of the map */
    map?: MapState
    /** List of layers to be displayed on the map */
    layers?: LayerState[]
}

export interface GetAppStateResponse {
    /** Version of the state object: `major.minor` */
    version: string
    state: StateV1
    /** When true the application state version is deprecated */
    deprecated?: boolean
    /** Warning message about deprecation flag */
    warning?: string
}

export type ValidationErrorCtx = { [key: string]: unknown }

export interface ValidationError {
    loc: (string | number)[]
    msg: string
    type: string
    input?: unknown
    ctx?: ValidationErrorCtx
}

export interface HTTPValidationError {
    detail?: ValidationError[]
}

export interface SaveAppStateRequest {
    /** Version of the state object: `major.minor` */
    version: string
    /** State of the application to save */
    state: StateV1
}

export interface SaveAppStateResponse {
    /**
     * ID of the saved state, to be used to retrieve the state later
     * @minLength 16
     * @maxLength 16
     */
    id: string
    /** When true the application state version provided is deprecated */
    deprecated?: boolean
    /** Warning message about deprecation flag */
    warning?: string
}
