/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import { Checker, GetAppStateResponse, SaveAppStateResponse } from '../model'
import type { ErrorResponse, SaveAppStateRequest } from '../model'

/**
 * Simple checker endpoint to be used by kubernetes probes
 * @summary Kubernetes Probe
 */
export type getCheckerCheckerGetResponse200 = {
    data: Checker
    status: 200
}

export type getCheckerCheckerGetResponseSuccess = getCheckerCheckerGetResponse200 & {
    headers: Headers
}
export type getCheckerCheckerGetResponse = getCheckerCheckerGetResponseSuccess

export const getGetCheckerCheckerGetUrl = () => {
    return `http://127.0.0.1:8000/checker`
}

export const getCheckerCheckerGet = async (
    options?: RequestInit
): Promise<getCheckerCheckerGetResponse> => {
    const res = await fetch(getGetCheckerCheckerGetUrl(), {
        ...options,
        method: 'GET',
    })

    const body = [204, 205, 304].includes(res.status) ? null : await res.text()

    const parsedBody = body ? JSON.parse(body) : {}
    const data = Checker.parse(parsedBody)
    return { data, status: res.status, headers: res.headers } as getCheckerCheckerGetResponse
}

/**
 * Save the given application state
 * @summary Save Application State
 */
export type postAppStateApiStatePostResponse200 = {
    data: SaveAppStateResponse
    status: 200
}

export type postAppStateApiStatePostResponse400 = {
    data: ErrorResponse
    status: 400
}

export type postAppStateApiStatePostResponseSuccess = postAppStateApiStatePostResponse200 & {
    headers: Headers
}
export type postAppStateApiStatePostResponseError = postAppStateApiStatePostResponse400 & {
    headers: Headers
}

export type postAppStateApiStatePostResponse =
    | postAppStateApiStatePostResponseSuccess
    | postAppStateApiStatePostResponseError

export const getPostAppStateApiStatePostUrl = () => {
    return `http://127.0.0.1:8000/api/state`
}

export const postAppStateApiStatePost = async (
    saveAppStateRequest: SaveAppStateRequest,
    options?: RequestInit
): Promise<postAppStateApiStatePostResponse> => {
    const res = await fetch(getPostAppStateApiStatePostUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(saveAppStateRequest),
    })

    const body = [204, 205, 304].includes(res.status) ? null : await res.text()

    const parsedBody = body ? JSON.parse(body) : {}
    const data = SaveAppStateResponse.parse(parsedBody)
    return { data, status: res.status, headers: res.headers } as postAppStateApiStatePostResponse
}

/**
 * Retrieve an application state by ID
 * @summary Get Application State
 */
export type getAppStateApiStateStateIdGetResponse200 = {
    data: GetAppStateResponse
    status: 200
}

export type getAppStateApiStateStateIdGetResponse400 = {
    data: ErrorResponse
    status: 400
}

export type getAppStateApiStateStateIdGetResponse404 = {
    data: ErrorResponse
    status: 404
}

export type getAppStateApiStateStateIdGetResponseSuccess =
    getAppStateApiStateStateIdGetResponse200 & {
        headers: Headers
    }
export type getAppStateApiStateStateIdGetResponseError = (
    | getAppStateApiStateStateIdGetResponse400
    | getAppStateApiStateStateIdGetResponse404
) & {
    headers: Headers
}

export type getAppStateApiStateStateIdGetResponse =
    | getAppStateApiStateStateIdGetResponseSuccess
    | getAppStateApiStateStateIdGetResponseError

export const getGetAppStateApiStateStateIdGetUrl = (stateId: string) => {
    return `http://127.0.0.1:8000/api/state/${stateId}`
}

export const getAppStateApiStateStateIdGet = async (
    stateId: string,
    options?: RequestInit
): Promise<getAppStateApiStateStateIdGetResponse> => {
    const res = await fetch(getGetAppStateApiStateStateIdGetUrl(stateId), {
        ...options,
        method: 'GET',
    })

    const body = [204, 205, 304].includes(res.status) ? null : await res.text()

    const parsedBody = body ? JSON.parse(body) : {}
    const data = GetAppStateResponse.parse(parsedBody)
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as getAppStateApiStateStateIdGetResponse
}
