/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
    it later on.

 * OpenAPI spec version: v0.2.0-beta.10
 */
export interface Checker {
    /** True when the probe is successful, false otherwise */
    success: boolean
    /** Failure explanation in case of failure, otherwise OK */
    message: string
    /** Version of the service */
    version: string
}

export interface ErrorResponse {
    /** Error text code */
    error: string
    /** Error message */
    message: string
    /** Details on the error */
    detail?: unknown | null
}

export interface MapState {
    /** Center of the map in [x, y] coordinates in lv95 / EPSG:2056 */
    center?: [number, number] | null
    /** Zoom level of the map */
    zoom?: number | null
    /** Rotation of the map in radian */
    rotation?: number | null
}

export type LayerTypeEnum = (typeof LayerTypeEnum)[keyof typeof LayerTypeEnum]

export const LayerTypeEnum = {
    dataset: 'dataset',
    gpx: 'gpx',
    kml: 'kml',
} as const

export interface TimeDimension {
    /** Current selected time value */
    currentValue?: string | 'current' | null
}

export interface LayerDimensionsState {
    /** Time dimension with current value */
    time?: TimeDimension
}

export interface LayerStateOutput {
    /**
     * URL of the layer to be displayed on the map
     * @minLength 1
     */
    layerUrl: string
    /** Type of the layer (e.g. dataset, gpx, kml) */
    type: LayerTypeEnum
    /** Whether the layer is visible on the map */
    isVisible?: boolean | null
    /** Opacity of the layer (between 0 and 1) */
    opacity?: number | null
    /** Dimensions of the layer (e.g. time dimension with current value) */
    dimensions?: LayerDimensionsState
}

/**
 * State object of the application
 */
export interface StateV1Output {
    /** State of the map */
    map?: MapState
    /** List of layers to be displayed on the map */
    layers?: LayerStateOutput[]
}

export interface GetAppStateResponse {
    state: StateV1Output
    /** When true the application state version is deprecated */
    deprecated?: boolean
    /** Warning message about deprecation flag */
    warning?: string
}

export type ValidationErrorCtx = { [key: string]: unknown }

export interface ValidationError {
    loc: (string | number)[]
    msg: string
    type: string
    input?: unknown
    ctx?: ValidationErrorCtx
}

export interface HTTPValidationError {
    detail?: ValidationError[]
}

export interface LayerStateInput {
    /**
     * URL of the layer to be displayed on the map
     * @minLength 1
     */
    layerUrl: string
    /** Type of the layer (e.g. dataset, gpx, kml) */
    type: LayerTypeEnum
    /** Whether the layer is visible on the map */
    isVisible?: boolean | null
    /** Opacity of the layer (between 0 and 1) */
    opacity?: number | null
    /** Dimensions of the layer (e.g. time dimension with current value) */
    dimensions?: LayerDimensionsState
}

/**
 * State object of the application
 */
export interface StateV1Input {
    /** State of the map */
    map?: MapState
    /** List of layers to be displayed on the map */
    layers?: LayerStateInput[]
}

export interface SaveAppStateRequest {
    /** State of the application to save */
    state: StateV1Input
}

export interface SaveAppStateResponse {
    /**
     * ID of the saved state, to be used to retrieve the state later
     * @minLength 16
     * @maxLength 16
     */
    id: string
    /** When true the application state version provided is deprecated */
    deprecated?: boolean
    /** Warning message about deprecation flag */
    warning?: string
}
