/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * Service State Portal
 * This service allow the web-portal application to save its state and retrieve
        it later on.

 * OpenAPI spec version: v0.2.0-beta.2-6-g9076d04
 */
import type { RequestHandlerOptions } from 'msw'

import { faker } from '@faker-js/faker'
import { HttpResponse, http } from 'msw'

import type {
    Checker,
    GetAppStateResponse,
    SaveAppStateResponse,
} from './serviceStatePortal.schemas'

import { LayerTypeEnum } from './serviceStatePortal.schemas'

export const getGetCheckerCheckerGetResponseMock = (
    overrideResponse: Partial<Extract<Checker, object>> = {}
): Checker => ({
    success: faker.datatype.boolean(),
    message: faker.string.alpha({ length: { min: 10, max: 20 } }),
    version: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getPostAppStateApiStatePostResponseMock = (
    overrideResponse: Partial<Extract<SaveAppStateResponse, object>> = {}
): SaveAppStateResponse => ({
    id: faker.string.alpha({ length: { min: 16, max: 16 } }),
    deprecated: faker.datatype.boolean(),
    warning: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getGetAppStateApiStateStateIdGetResponseMock = (
    overrideResponse: Partial<Extract<GetAppStateResponse, object>> = {}
): GetAppStateResponse => ({
    version: faker.string.alpha({ length: { min: 10, max: 20 } }),
    state: {
        map: faker.helpers.arrayElement([
            {
                center: [],
                zoom: faker.number.float({ min: 1, max: 13, fractionDigits: 2 }),
                rotation: faker.number.float({ min: 0, max: 6.283185307179586, fractionDigits: 2 }),
            },
            undefined,
        ]),
        layers: faker.helpers.arrayElement([
            Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(
                () => ({
                    layerUrl: faker.internet.url(),
                    type: faker.helpers.arrayElement(Object.values(LayerTypeEnum)),
                    isVisible: faker.datatype.boolean(),
                    opacity: faker.number.float({ min: 0, max: 1, fractionDigits: 2 }),
                    dimensions: faker.helpers.arrayElement([
                        {
                            time: faker.helpers.arrayElement([
                                {
                                    currentValue: faker.helpers.arrayElement([
                                        faker.date.past().toISOString().slice(0, 19) + 'Z',
                                        'current',
                                    ]),
                                },
                                undefined,
                            ]),
                        },
                        undefined,
                    ]),
                })
            ),
            undefined,
        ]),
    },
    deprecated: faker.datatype.boolean(),
    warning: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
})

export const getGetCheckerCheckerGetMockHandler = (
    overrideResponse?:
        | Checker
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Checker> | Checker),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/checker',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetCheckerCheckerGetResponseMock(),
                { status: 200 }
            )
        },
        options
    )
}

export const getPostAppStateApiStatePostMockHandler = (
    overrideResponse?:
        | SaveAppStateResponse
        | ((
              info: Parameters<Parameters<typeof http.post>[1]>[0]
          ) => Promise<SaveAppStateResponse> | SaveAppStateResponse),
    options?: RequestHandlerOptions
) => {
    return http.post(
        '*/api/state',
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getPostAppStateApiStatePostResponseMock(),
                { status: 200 }
            )
        },
        options
    )
}

export const getGetAppStateApiStateStateIdGetMockHandler = (
    overrideResponse?:
        | GetAppStateResponse
        | ((
              info: Parameters<Parameters<typeof http.get>[1]>[0]
          ) => Promise<GetAppStateResponse> | GetAppStateResponse),
    options?: RequestHandlerOptions
) => {
    return http.get(
        '*/api/state/:stateId',
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === 'function'
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetAppStateApiStateStateIdGetResponseMock(),
                { status: 200 }
            )
        },
        options
    )
}

export const getServiceStatePortalMock = () => [
    getGetCheckerCheckerGetMockHandler(),
    getPostAppStateApiStatePostMockHandler(),
    getGetAppStateApiStateStateIdGetMockHandler(),
]
