<script setup lang="ts">
import { LV95 } from '@swissgeo/coordinates'
import ScaleLine from 'ol/control/ScaleLine'
import { storeToRefs } from 'pinia'
import { computed, ref, toValue, useTemplateRef, watch } from 'vue'

import { useMapStore } from '@/stores/map'
import usePositionStore from '@/stores/position'

const scaleLineElement = useTemplateRef<HTMLElement>('scaleLineElement')

const positionStore = usePositionStore()
const mapStore = useMapStore()

const showScaleLine = computed<boolean>(
    () => positionStore.projection.epsg === LV95.epsg || positionStore.zoom >= 9
)

const fontSizeFactor = ref<number>(1)
const fontSize = computed(() => `${(10 * fontSizeFactor.value).toFixed(0)}px`)
const { olMap } = storeToRefs(mapStore)

watch(
    () => olMap,
    () => {
        const olMapInstance = toValue(olMap)
        if (!olMapInstance) {
            return
        }

        olMapInstance.once('postrender', () => {
            // The maximum width of the scale is a third of the map shortest side
            let scaleMaxWidth = 300
            const mapSize = olMapInstance.getSize()

            if (mapSize && mapSize.length === 2) {
                const shortestSide = Math.min(mapSize[0], mapSize[1])

                // A factor is applied to the font size and the every element defined with the
                // unit 'em' is css to keep bar and text large enough on large prints
                fontSizeFactor.value = 0.5 * (shortestSide / 1000) + 0.5
                scaleMaxWidth = shortestSide / 3
            }

            const scaleLine = new ScaleLine({
                className: 'scale-bar',
                bar: true,
                maxWidth: scaleMaxWidth,
                minWidth: scaleMaxWidth * 0.66, // the min size is 2/3rd of the max size
            })

            if (scaleLineElement.value) {
                scaleLine.setTarget(scaleLineElement.value)
            }
            olMapInstance.addControl(scaleLine)
        })
    },
    {
        immediate: true,
    }
)
</script>

<template>
    <!-- The initialization will fail with `v-if` if initial zoom is too low. -->
    <div
        v-show="showScaleLine"
        ref="scaleLineElement"
        class="scale-line-container-print absolute bg-white"
        data-testid="scaleline"
        :style="{
            fontSize: fontSize,
        }"
    />
</template>

<style>
/*
    Must be unscoped, as the scaleLine is generated by OpenLayers on the fly
*/
.scale-line-container-print {
    padding: 1em 3em 1.5em 1em;
    bottom: -1px;
    left: -1px;
}

.scale-line-container-print .scale-line-inner {
    max-width: 100%;
    border: 1px solid black;
    border-top: none;
    text-align: center;
    font-weight: bold;
    color: black;
    background-color: rgba(white, 0.7);
}

.scale-line-container-print .scale-bar {
    --scale-border-color: black;
    --scale-bar-primary: black;
    --scale-bar-secondary: light-gray;
    --font-size: 8px;
}

.scale-line-container-print .scale-bar .scale-bar-inner {
    display: flex;
}

.scale-line-container-print .scale-bar .ol-scale-step-marker {
    width: 1px;
    height: 2em;
    background-color: black;
    float: right;
    z-index: 10;
}

.scale-line-container-print .scale-bar-inner > div > .ol-scale-step-marker {
    top: -1em !important;
}

.scale-line-container-print .scale-bar .ol-scale-step-text {
    position: absolute;
    bottom: -0.25em;
    font-size: 1em;
    z-index: 11;
    color: black;
    height: 1em;
}

.scale-line-container-print .ol-scale-singlebar {
    position: relative;
    height: 1em;
    z-index: 9;
    box-sizing: border-box;
    border-top: 1px solid #000 !important;
    border-bottom: 1px solid #000 !important;
    border-left: 0px solid #000 !important;
    border-right: 0px solid #000 !important;
}

.scale-line-container-print .ol-scale-singlebar-even {
    background-color: #ffffff !important;
}

.scale-line-container-print .ol-scale-singlebar-odd {
    background-color: #000000 !important;
}

.scale-line-container-print .scale-bar {
    position: relative;
}

@media print {
    .scale-line-container-print .scale-bar,
    .scale-line-container-print .scale-line-container,
    .scale-line-container-print .ol-scale-singlebar,
    .scale-line-container-print .ol-scale-singlebar-even,
    .scale-line-container-print .ol-scale-singlebar-odd,
    .scale-line-container-print .ol-scale-step-marker,
    .scale-line-container-print .ol-scale-step-text,
    .scale-line-container-print .ol-scale-text {
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }

    .scale-line-container-print .ol-scale-singlebar {
        border-top: 1px solid #000 !important;
        border-bottom: 1px solid #000 !important;
        border-left: 0px solid #000 !important;
        border-right: 0px solid #000 !important;
    }

    .scale-line-container-print .ol-scale-singlebar-even {
        background: #fff !important;
    }

    .scale-line-container-print .ol-scale-singlebar-odd {
        background: #000 !important;
    }

    .scale-line-container-print .ol-scale-step-marker,
    .scale-line-container-print .ol-scale-step-text,
    .scale-line-container-print .ol-scale-text {
        color: #000 !important;
        background: transparent !important;
    }

    .scale-line-container-print .ol-scale-step-marker {
        width: 1px !important;
        min-width: 1px !important;
        background-color: #000 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
    }
}
</style>
