<script setup lang="ts">
import type { Map } from 'ol'
import { LV95 } from '@swissgeo/coordinates'
import log from '@swissgeo/log'
import ScaleLine from 'ol/control/ScaleLine'
import { computed, inject, onMounted, ref, toValue, useTemplateRef } from 'vue'

import usePositionStore from '@/stores/position'


const scaleLineElement = useTemplateRef<HTMLElement>('scaleLineElement')

const positionStore = usePositionStore()

const showScaleLine = computed<boolean>(
    () => positionStore.projection.epsg === LV95.epsg || positionStore.zoom >= 9
)

const olMap = toValue(inject<Map>('olMap'))
if (!olMap) {
    log.error('OpenLayersMap is not available')
    throw new Error('OpenLayersMap is not available')
}

const fontSizeFactor = ref<number>(1)
const fontSize = computed(() => `${(10 * fontSizeFactor.value).toFixed(0)}px`)

onMounted(() => {
    olMap.once('postrender', () => {
        // The maximum width of the scale is a third of the map shortest side
        let scaleMaxWidth = 300
        const mapSize = olMap.getSize()

        if (mapSize && mapSize.length === 2) {
            const shortestSide = Math.min((mapSize[0] as number), (mapSize[1] as number))

            // A factor is applied to the font size and the every element defined with the
            // unit 'em' is css to keep bar and text large enough on large prints
            fontSizeFactor.value = 0.5 * (shortestSide/1000) + 0.5
            scaleMaxWidth = shortestSide / 3
        }

        const scaleLine = new ScaleLine({
            className:  "scale-bar",
            bar: true,
            maxWidth: scaleMaxWidth,
            minWidth: scaleMaxWidth * 0.66, // the min size is 2/3rd of the max size
        })

        if (scaleLineElement.value) {
            scaleLine.setTarget(scaleLineElement.value)
        }
        olMap.addControl(scaleLine)
    })
})
</script>

<template>
    <!-- The initialization will fail with `v-if` if initial zoom is too low. -->
    <div
        v-show="showScaleLine"
        ref="scaleLineElement"
        class="scale-line-container absolute bottom-0 left-0 bg-white"
        data-cy="scaleline"
        :style="{
            fontSize: fontSize,
        }"
    />
</template>

<style>
/*
    Must be unscoped, as the scaleLine is generated by OpenLayers on the fly
*/
.scale-line-container {
    padding: 1em 3em 1.5em 1em;
}

.scale-line-container .scale-line-inner {
    max-width: 100%;
    border: 1px solid black;
    border-top: none;
    text-align: center;
    font-weight: bold;
    color: black;
    background-color: rgba(white, 0.7);
}

.scale-bar {
    --scale-border-color: black;
    --scale-bar-primary: black;
    --scale-bar-secondary: light-gray;
    --font-size: 8px;
}

.scale-bar .scale-bar-inner {
    display: flex;
}


.scale-bar .ol-scale-step-marker {
    width: 1px;
    height: 2em;
    background-color: black;
    float: right;
    z-index: 10;
}

.scale-bar-inner > div > .ol-scale-step-marker {
    top: -1em !important;
}

.scale-bar .ol-scale-step-text {
    position: absolute;
    bottom: -0.25em;
    font-size: 1em;
    z-index: 11;
    color: black;
    height: 1em;
}

.ol-scale-singlebar {
    position: relative;
    height: 1em;
    z-index: 9;
    box-sizing: border-box;
    border-top: 1px solid #000 !important;
    border-bottom: 1px solid #000 !important;
    border-left: 0px solid #000 !important;
    border-right: 0px solid #000 !important;
}

.ol-scale-singlebar-even {
    background-color: #FFFFFF !important;
}

.ol-scale-singlebar-odd {
    background-color: #000000 !important;
}

.scale-bar {
    position: relative;
}

@media print {
  .scale-bar,
  .scale-line-container,
  .ol-scale-singlebar,
  .ol-scale-singlebar-even,
  .ol-scale-singlebar-odd,
  .ol-scale-step-marker,
  .ol-scale-step-text,
  .ol-scale-text {
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }

  .ol-scale-singlebar {
    border-top: 1px solid #000 !important;
    border-bottom: 1px solid #000 !important;
    border-left: 0px solid #000 !important;
    border-right: 0px solid #000 !important;
  }

  .ol-scale-singlebar-even {
    background: #fff !important;
  }

  .ol-scale-singlebar-odd {
    background: #000 !important;
  }

  .ol-scale-step-marker,
  .ol-scale-step-text,
  .ol-scale-text {
    color: #000 !important;
    background: transparent !important;
  }

  .ol-scale-step-marker {
    width: 1px !important;
    min-width: 1px !important;
    background-color: #000 !important;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
}
</style>
