<script setup lang="ts">
import type { Map } from "ol";

import { LV95 } from "@swissgeo/coordinates";
import log from "@swissgeo/log";
import ScaleLine from "ol/control/ScaleLine";
import {
  computed,
  inject,
  onBeforeUnmount,
  onMounted,
  toValue,
  useTemplateRef,
} from "vue";

import usePositionStore from "@/stores/position";

const {
  scaleType = "line",
  minWidth = 100,
  withRelativeSize = false,
} = defineProps<{
  scaleType?: "line" | "bar";
  minWidth?: number;
  withRelativeSize?: boolean;
}>();

const scaleLineElement = useTemplateRef<HTMLElement>("scaleLineElement");

const positionStore = usePositionStore();

const showScaleLine = computed<boolean>(
  () => positionStore.projection.epsg === LV95.epsg || positionStore.zoom >= 9,
);

const scaleLine = new ScaleLine({
  className: `scale-${scaleType}`,
  bar: scaleType === "bar",
  minWidth: minWidth,
});

const olMap = toValue(inject<Map>("olMap"));
if (!olMap) {
  log.error("OpenLayersMap is not available");
  throw new Error("OpenLayersMap is not available");
}

onMounted(() => {
  if (scaleLineElement.value) {
    scaleLine.setTarget(scaleLineElement.value);
  }
  olMap.addControl(scaleLine);
});

onBeforeUnmount(() => olMap.removeControl(scaleLine));
</script>

<template>
  <!-- The initialization will fail with `v-if` if initial zoom is too low. -->
  <div
    v-show="showScaleLine"
    ref="scaleLineElement"
    class="scale-line-container fixed bottom-4 left-20"
    :class="{ 'with-relative-size': withRelativeSize }"
    data-testid="scaleline"
  />
</template>

<style>
/* Must be unscoped, as the scaleLine is generated by OpenLayers on the fly */
.scale-line-container .scale-line-inner {
  @apply max-w-full border-2 border-t-0 border-black bg-white/70 text-center font-bold text-black;
}

.scale-bar {
  @apply relative;
  --scale-border-color: black;
  --scale-bar-primary: black;
  --scale-bar-secondary: lightgray;
  --font-size: 8px;
}

.scale-bar .scale-bar-inner {
  @apply flex;
}

.scale-bar.with-relative-size {
  --font-size: max(max(0.8vw, 0.8vh), 8px);
}

.scale-bar .ol-scale-step-marker {
  @apply z-10 float-right w-px;
  height: calc(2 * var(--font-size));
  background-color: var(--scale-border-color);
}

.scale-bar .ol-scale-step-text {
  @apply absolute z-11;
  bottom: calc(-1 * var(--font-size));
  font-size: var(--font-size);
  color: var(--scale-border-color);
}

.scale-bar .ol-scale-text {
  @apply absolute text-center;
  bottom: calc(2 * var(--font-size));
  font-size: var(--font-size);
  color: var(--scale-border-color);
}

.ol-scale-singlebar {
  @apply relative z-9 box-border border;
  height: var(--font-size);
  border-color: var(--scale-border-color);
}

.ol-scale-singlebar-even {
  background-color: var(--scale-bar-secondary);
}

.ol-scale-singlebar-odd {
  background-color: var(--scale-bar-primary);
}
</style>
