<script setup lang="ts">
import type { Map } from "ol";

import { LV95 } from "@swissgeo/coordinates";
import log from "@swissgeo/log";
import ScaleLine from "ol/control/ScaleLine";
import {
  computed,
  inject,
  onBeforeUnmount,
  onMounted,
  useTemplateRef,
  Ref
} from "vue";

import usePositionStore from "@/stores/position";

const {
  scaleType = "line",
  minWidth = 100,
  withRelativeSize = false,
} = defineProps<{
  scaleType?: "line" | "bar";
  minWidth?: number;
  withRelativeSize?: boolean;
}>();

const scaleLineElement = useTemplateRef<HTMLElement>("scaleLineElement");

const positionStore = usePositionStore();

const showScaleLine = computed<boolean>(
  () => positionStore.projection.epsg === LV95.epsg || positionStore.zoom >= 9,
);

const scaleLine = new ScaleLine({
  className: `scale-${scaleType}`,
  bar: scaleType === "bar",
  minWidth: minWidth,
});

const olMap = inject<Ref<Map>>("olMap");

if (!olMap) {
  log.error("OpenLayersMap is not available");
  throw new Error("OpenLayersMap is not available");
}

onMounted(() => {
  if (scaleLineElement.value) {
    scaleLine.setTarget(scaleLineElement.value);
  }
  console.log(olMap);
  olMap.value.addControl(scaleLine);
});

onBeforeUnmount(() => olMap.value.removeControl(scaleLine));
</script>

<template>
    <!-- The initialization will fail with `v-if` if initial zoom is too low. -->
    <div
        v-show="showScaleLine"
        ref="scaleLineElement"
        class="scale-line-container"
        :class="withRelativeSize"
        data-cy="scaleline"
    />
</template>

<style>
/* Must be unscoped, as the scaleLine is generated by OpenLayers on the fly */

.scale-line-container {
  .scale-line-inner {
    max-width: 100%;
    border: 2px solid black;
    border-top: none;
    text-align: center;
    font-weight: bold;
    color: black;
    background-color: rgba(white, 0.7);
  }
}

.scale-bar {
  --scale-border-color: black;
  --scale-bar-primary: black;
  --scale-bar-secondary: light-gray;
  --font-size: 8px;
}

.scale-bar .scale-bar-inner {
  display: flex;
}

.scale-bar.with-relative-size {
  --font-size: max(max(0.8vw, 0.8vh), 8px);
}

.scale-bar .ol-scale-step-marker {
  width: 1px;
  height: calc(2 * var(--font-size));
  background-color: var(--scale-bar-border-color);
  float: right;
  z-index: 10;
}

.scale-bar .ol-scale-step-text {
  position: absolute;
  bottom: calc(-1 * var(--font-size));
  font-size: var(--font-size);
  z-index: 11;
  color: var(--scale-bar-border-color);
}

.scale-bar .ol-scale-text {
  position: absolute;
  font-size: var(--font-size);
  text-align: center;
  bottom: calc(2 * var(--font-size));
  color: var(--scale-bar-border-color);
}

.ol-scale-singlebar {
  position: relative;
  height: var(--font-size);
  z-index: 9;
  box-sizing: border-box;
  border: 1px solid var(--scale-bar-border-color);
}

.ol-scale-singlebar-even {
  background-color: var(--scale-bar-secondary);
}

.ol-scale-singlebar-odd {
  background-color: var(--scale-bar-primary);
}

.scale-bar {
  position: relative;
}
</style>
