// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://www.dev.sgdi.tech" | (string & {});
};

/**
 * Body_create_drawing_api_wps_v1_drawings_post
 */
export type BodyCreateDrawingApiWpsV1DrawingsPost = {
  /**
   * File
   *
   * The KMZ file to upload. Only KMZ files are accepted.
   */
  file: Blob | File;
  /**
   * Sha256
   *
   * SHA-256 hex digest of the KMZ file bytes (not of the multipart body), computed by the client before upload. Case-insensitive.
   */
  sha256: string;
};

/**
 * Body_update_drawing_api_wps_v1_drawings__drawing_id__put
 */
export type BodyUpdateDrawingApiWpsV1DrawingsDrawingIdPut = {
  /**
   * File
   *
   * The KMZ file to upload. Only KMZ files are accepted.
   */
  file: Blob | File;
  /**
   * Sha256
   *
   * SHA-256 hex digest of the KMZ file bytes (not of the multipart body), computed by the client before upload. Case-insensitive.
   */
  sha256: string;
};

/**
 * DrawingsCreateResponse
 *
 * Response model returned after a successful drawing upload.
 *
 * Attributes:
 * id: Unique drawing identifier (UUID4).
 * admin_id: Admin identifier required to update the drawing.
 * s3_url: HTTP URL where the KMZ file can be accessed.
 */
export type DrawingsCreateResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Admin Id
   */
  admin_id: string;
  /**
   * S3 Url
   */
  s3_url: string;
};

/**
 * DrawingsMetadataResponse
 *
 * Response model describing a stored drawing without transferring its content.
 *
 * Attributes:
 * id: Unique drawing identifier (UUID4).
 * original_filename: Name of the file as sent by the client on the last
 * upload, or None for drawings stored before this was recorded.
 * created_at: UTC ISO-8601 timestamp of the initial upload.
 * modified_at: UTC ISO-8601 timestamp of the last update.
 */
export type DrawingsMetadataResponse = {
  /**
   * Id
   *
   * Unique drawing identifier
   */
  id: string;
  /**
   * Original Filename
   *
   * Name of the uploaded file as provided by the client, or null when unknown
   */
  original_filename?: string | null;
  /**
   * Created At
   *
   * Creation timestamp
   */
  created_at: string;
  /**
   * Modified At
   *
   * Last update timestamp
   */
  modified_at: string;
};

/**
 * DrawingsUpdateResponse
 *
 * Response model returned after a successful drawing update.
 *
 * Extends the creation response with creation and last-update timestamps.
 *
 * Attributes:
 * created_at: UTC ISO-8601 timestamp of the initial upload.
 * modified_at: UTC ISO-8601 timestamp of the last update.
 */
export type DrawingsUpdateResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Admin Id
   */
  admin_id: string;
  /**
   * S3 Url
   */
  s3_url: string;
  /**
   * Created At
   *
   * Creation timestamp
   */
  created_at: string;
  /**
   * Modified At
   *
   * Last update timestamp
   */
  modified_at: string;
};

/**
 * ErrorResponse
 *
 * Standard error response body.
 *
 * Attributes:
 * detail: Human-readable description of the error.
 */
export type ErrorResponse = {
  /**
   * Detail
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type CreateDrawingApiWpsV1DrawingsPostData = {
  body: BodyCreateDrawingApiWpsV1DrawingsPost;
  path?: never;
  query?: never;
  url: "/api/wps/v1/drawings";
};

export type CreateDrawingApiWpsV1DrawingsPostErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Content Too Large
   */
  413: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CreateDrawingApiWpsV1DrawingsPostError =
  CreateDrawingApiWpsV1DrawingsPostErrors[keyof CreateDrawingApiWpsV1DrawingsPostErrors];

export type CreateDrawingApiWpsV1DrawingsPostResponses = {
  /**
   * Successful Response
   */
  201: DrawingsCreateResponse;
};

export type CreateDrawingApiWpsV1DrawingsPostResponse =
  CreateDrawingApiWpsV1DrawingsPostResponses[keyof CreateDrawingApiWpsV1DrawingsPostResponses];

export type DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteData = {
  body?: never;
  path: {
    /**
     * Drawing Id
     */
    drawing_id: string;
  };
  query?: never;
  url: "/api/wps/v1/drawings/{drawing_id}";
};

export type DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteError =
  DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteErrors[keyof DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteErrors];

export type DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteResponse =
  DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteResponses[keyof DeleteDrawingApiWpsV1DrawingsDrawingIdDeleteResponses];

export type GetDrawingApiWpsV1DrawingsDrawingIdGetData = {
  body?: never;
  path: {
    /**
     * Drawing Id
     */
    drawing_id: string;
  };
  query?: never;
  url: "/api/wps/v1/drawings/{drawing_id}";
};

export type GetDrawingApiWpsV1DrawingsDrawingIdGetErrors = {
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetDrawingApiWpsV1DrawingsDrawingIdGetError =
  GetDrawingApiWpsV1DrawingsDrawingIdGetErrors[keyof GetDrawingApiWpsV1DrawingsDrawingIdGetErrors];

export type GetDrawingApiWpsV1DrawingsDrawingIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateDrawingApiWpsV1DrawingsDrawingIdPutData = {
  body: BodyUpdateDrawingApiWpsV1DrawingsDrawingIdPut;
  path: {
    /**
     * Drawing Id
     */
    drawing_id: string;
  };
  query?: never;
  url: "/api/wps/v1/drawings/{drawing_id}";
};

export type UpdateDrawingApiWpsV1DrawingsDrawingIdPutErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Content Too Large
   */
  413: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type UpdateDrawingApiWpsV1DrawingsDrawingIdPutError =
  UpdateDrawingApiWpsV1DrawingsDrawingIdPutErrors[keyof UpdateDrawingApiWpsV1DrawingsDrawingIdPutErrors];

export type UpdateDrawingApiWpsV1DrawingsDrawingIdPutResponses = {
  /**
   * Successful Response
   */
  200: DrawingsUpdateResponse;
};

export type UpdateDrawingApiWpsV1DrawingsDrawingIdPutResponse =
  UpdateDrawingApiWpsV1DrawingsDrawingIdPutResponses[keyof UpdateDrawingApiWpsV1DrawingsDrawingIdPutResponses];

export type CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetData = {
  body?: never;
  path: {
    /**
     * Drawing Id
     */
    drawing_id: string;
  };
  query?: never;
  url: "/api/wps/v1/drawings/{drawing_id}/check-auth";
};

export type CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetError =
  CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetErrors[keyof CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetErrors];

export type CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetResponse =
  CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetResponses[keyof CheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetResponses];

export type GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetData = {
  body?: never;
  path: {
    /**
     * Drawing Id
     */
    drawing_id: string;
  };
  query?: never;
  url: "/api/wps/v1/drawings/{drawing_id}/metadata";
};

export type GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetErrors = {
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
};

export type GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetError =
  GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetErrors[keyof GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetErrors];

export type GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetResponses = {
  /**
   * Successful Response
   */
  200: DrawingsMetadataResponse;
};

export type GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetResponse =
  GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetResponses[keyof GetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetResponses];
