// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * Body_create_drawing_api_wps_v1_drawings_post
 */
export const zBodyCreateDrawingApiWpsV1DrawingsPost = z.object({
  file: z.string(),
  sha256: z.string().regex(/^[0-9a-fA-F]{64}$/),
});

/**
 * Body_update_drawing_api_wps_v1_drawings__drawing_id__put
 */
export const zBodyUpdateDrawingApiWpsV1DrawingsDrawingIdPut = z.object({
  file: z.string(),
  sha256: z.string().regex(/^[0-9a-fA-F]{64}$/),
});

/**
 * DrawingsCreateResponse
 *
 * Response model returned after a successful drawing upload.
 *
 * Attributes:
 * id: Unique drawing identifier (UUID4).
 * admin_id: Admin identifier required to update the drawing.
 * s3_url: HTTP URL where the KMZ file can be accessed.
 */
export const zDrawingsCreateResponse = z.object({
  id: z.uuid(),
  admin_id: z.uuid(),
  s3_url: z.url().min(1).max(2083),
});

/**
 * DrawingsMetadataResponse
 *
 * Response model describing a stored drawing without transferring its content.
 *
 * Attributes:
 * id: Unique drawing identifier (UUID4).
 * original_filename: Name of the file as sent by the client on the last
 * upload, or None for drawings stored before this was recorded.
 * created_at: UTC ISO-8601 timestamp of the initial upload.
 * modified_at: UTC ISO-8601 timestamp of the last update.
 */
export const zDrawingsMetadataResponse = z.object({
  id: z.uuid(),
  original_filename: z.string().nullish(),
  created_at: z.iso.datetime(),
  modified_at: z.iso.datetime(),
});

/**
 * DrawingsUpdateResponse
 *
 * Response model returned after a successful drawing update.
 *
 * Extends the creation response with creation and last-update timestamps.
 *
 * Attributes:
 * created_at: UTC ISO-8601 timestamp of the initial upload.
 * modified_at: UTC ISO-8601 timestamp of the last update.
 */
export const zDrawingsUpdateResponse = z.object({
  id: z.uuid(),
  admin_id: z.uuid(),
  s3_url: z.url().min(1).max(2083),
  created_at: z.iso.datetime(),
  modified_at: z.iso.datetime(),
});

/**
 * ErrorResponse
 *
 * Standard error response body.
 *
 * Attributes:
 * detail: Human-readable description of the error.
 */
export const zErrorResponse = z.object({
  detail: z.string(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zCreateDrawingApiWpsV1DrawingsPostBody =
  zBodyCreateDrawingApiWpsV1DrawingsPost;

/**
 * Successful Response
 */
export const zCreateDrawingApiWpsV1DrawingsPostResponse =
  zDrawingsCreateResponse;

export const zDeleteDrawingApiWpsV1DrawingsDrawingIdDeletePath = z.object({
  drawing_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zDeleteDrawingApiWpsV1DrawingsDrawingIdDeleteResponse = z.void();

export const zGetDrawingApiWpsV1DrawingsDrawingIdGetPath = z.object({
  drawing_id: z.uuid(),
});

export const zUpdateDrawingApiWpsV1DrawingsDrawingIdPutBody =
  zBodyUpdateDrawingApiWpsV1DrawingsDrawingIdPut;

export const zUpdateDrawingApiWpsV1DrawingsDrawingIdPutPath = z.object({
  drawing_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zUpdateDrawingApiWpsV1DrawingsDrawingIdPutResponse =
  zDrawingsUpdateResponse;

export const zCheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetPath = z.object({
  drawing_id: z.uuid(),
});

/**
 * Successful Response
 */
export const zCheckAuthApiWpsV1DrawingsDrawingIdCheckAuthGetResponse = z.void();

export const zGetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetPath =
  z.object({
    drawing_id: z.uuid(),
  });

/**
 * Successful Response
 */
export const zGetDrawingMetadataApiWpsV1DrawingsDrawingIdMetadataGetResponse =
  zDrawingsMetadataResponse;
