---
# WARNING this file is managed by terraform and cannot be edited manually, see
# swissgeo/infra-terraform//github/swissgeo/modules/github-workflows-semver/main.tf
name: on-pr

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  semver:
    uses: swissgeo/.github/.github/workflows/pr-auto-semver.yml@main
